//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4016
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwaySSO.GWSSO {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GWSSO.UserStateServiceSoap")]
    public interface UserStateServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserState", ReplyAction="*")]
        GoodwaySSO.GWSSO.CreateUserStateResponse CreateUserState(GoodwaySSO.GWSSO.CreateUserStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserStateEx", ReplyAction="*")]
        GoodwaySSO.GWSSO.CreateUserStateExResponse CreateUserStateEx(GoodwaySSO.GWSSO.CreateUserStateExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserState", ReplyAction="*")]
        GoodwaySSO.GWSSO.CheckUserStateResponse CheckUserState(GoodwaySSO.GWSSO.CheckUserStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutUserState", ReplyAction="*")]
        GoodwaySSO.GWSSO.LogoutUserStateResponse LogoutUserState(GoodwaySSO.GWSSO.LogoutUserStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutUserStateEx", ReplyAction="*")]
        GoodwaySSO.GWSSO.LogoutUserStateExResponse LogoutUserStateEx(GoodwaySSO.GWSSO.LogoutUserStateExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPreOut", ReplyAction="*")]
        GoodwaySSO.GWSSO.SetPreOutResponse SetPreOut(GoodwaySSO.GWSSO.SetPreOutRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPreOutEx", ReplyAction="*")]
        GoodwaySSO.GWSSO.SetPreOutExResponse SetPreOutEx(GoodwaySSO.GWSSO.SetPreOutExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RefreshUserState", ReplyAction="*")]
        GoodwaySSO.GWSSO.RefreshUserStateResponse RefreshUserState(GoodwaySSO.GWSSO.RefreshUserStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        GoodwaySSO.GWSSO.GetUserInfoResponse GetUserInfo(GoodwaySSO.GWSSO.GetUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserInfo", ReplyAction="*")]
        GoodwaySSO.GWSSO.UpdateUserInfoResponse UpdateUserInfo(GoodwaySSO.GWSSO.UpdateUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserData", ReplyAction="*")]
        GoodwaySSO.GWSSO.GetUserDataResponse GetUserData(GoodwaySSO.GWSSO.GetUserDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserData", ReplyAction="*")]
        GoodwaySSO.GWSSO.UpdateUserDataResponse UpdateUserData(GoodwaySSO.GWSSO.UpdateUserDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserProp", ReplyAction="*")]
        GoodwaySSO.GWSSO.GetUserPropResponse GetUserProp(GoodwaySSO.GWSSO.GetUserPropRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserProp", ReplyAction="*")]
        GoodwaySSO.GWSSO.UpdateUserPropResponse UpdateUserProp(GoodwaySSO.GWSSO.UpdateUserPropRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDataNode", ReplyAction="*")]
        GoodwaySSO.GWSSO.GetUserDataNodeResponse GetUserDataNode(GoodwaySSO.GWSSO.GetUserDataNodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserDataNode", ReplyAction="*")]
        GoodwaySSO.GWSSO.SetUserDataNodeResponse SetUserDataNode(GoodwaySSO.GWSSO.SetUserDataNodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserState", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.CreateUserStateRequestBody Body;
        
        public CreateUserStateRequest() {
        }
        
        public CreateUserStateRequest(GoodwaySSO.GWSSO.CreateUserStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userName;
        
        public CreateUserStateRequestBody() {
        }
        
        public CreateUserStateRequestBody(string userInfo, string ip, string mac, string userId, string userName) {
            this.userInfo = userInfo;
            this.ip = ip;
            this.mac = mac;
            this.userId = userId;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.CreateUserStateResponseBody Body;
        
        public CreateUserStateResponse() {
        }
        
        public CreateUserStateResponse(GoodwaySSO.GWSSO.CreateUserStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserStateResult;
        
        public CreateUserStateResponseBody() {
        }
        
        public CreateUserStateResponseBody(string CreateUserStateResult) {
            this.CreateUserStateResult = CreateUserStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserStateEx", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.CreateUserStateExRequestBody Body;
        
        public CreateUserStateExRequest() {
        }
        
        public CreateUserStateExRequest(GoodwaySSO.GWSSO.CreateUserStateExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string loginMethod;
        
        public CreateUserStateExRequestBody() {
        }
        
        public CreateUserStateExRequestBody(string userInfo, string ip, string mac, string userId, string userName, string loginMethod) {
            this.userInfo = userInfo;
            this.ip = ip;
            this.mac = mac;
            this.userId = userId;
            this.userName = userName;
            this.loginMethod = loginMethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserStateExResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.CreateUserStateExResponseBody Body;
        
        public CreateUserStateExResponse() {
        }
        
        public CreateUserStateExResponse(GoodwaySSO.GWSSO.CreateUserStateExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserStateExResult;
        
        public CreateUserStateExResponseBody() {
        }
        
        public CreateUserStateExResponseBody(string CreateUserStateExResult) {
            this.CreateUserStateExResult = CreateUserStateExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserState", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.CheckUserStateRequestBody Body;
        
        public CheckUserStateRequest() {
        }
        
        public CheckUserStateRequest(GoodwaySSO.GWSSO.CheckUserStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public CheckUserStateRequestBody() {
        }
        
        public CheckUserStateRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.CheckUserStateResponseBody Body;
        
        public CheckUserStateResponse() {
        }
        
        public CheckUserStateResponse(GoodwaySSO.GWSSO.CheckUserStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserStateResult;
        
        public CheckUserStateResponseBody() {
        }
        
        public CheckUserStateResponseBody(bool CheckUserStateResult) {
            this.CheckUserStateResult = CheckUserStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserState", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.LogoutUserStateRequestBody Body;
        
        public LogoutUserStateRequest() {
        }
        
        public LogoutUserStateRequest(GoodwaySSO.GWSSO.LogoutUserStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public LogoutUserStateRequestBody() {
        }
        
        public LogoutUserStateRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.LogoutUserStateResponseBody Body;
        
        public LogoutUserStateResponse() {
        }
        
        public LogoutUserStateResponse(GoodwaySSO.GWSSO.LogoutUserStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogoutUserStateResult;
        
        public LogoutUserStateResponseBody() {
        }
        
        public LogoutUserStateResponseBody(bool LogoutUserStateResult) {
            this.LogoutUserStateResult = LogoutUserStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserStateExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserStateEx", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.LogoutUserStateExRequestBody Body;
        
        public LogoutUserStateExRequest() {
        }
        
        public LogoutUserStateExRequest(GoodwaySSO.GWSSO.LogoutUserStateExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserStateExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string logoutMethod;
        
        public LogoutUserStateExRequestBody() {
        }
        
        public LogoutUserStateExRequestBody(string passCode, string logoutMethod) {
            this.passCode = passCode;
            this.logoutMethod = logoutMethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserStateExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserStateExResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.LogoutUserStateExResponseBody Body;
        
        public LogoutUserStateExResponse() {
        }
        
        public LogoutUserStateExResponse(GoodwaySSO.GWSSO.LogoutUserStateExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserStateExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogoutUserStateExResult;
        
        public LogoutUserStateExResponseBody() {
        }
        
        public LogoutUserStateExResponseBody(bool LogoutUserStateExResult) {
            this.LogoutUserStateExResult = LogoutUserStateExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPreOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPreOut", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.SetPreOutRequestBody Body;
        
        public SetPreOutRequest() {
        }
        
        public SetPreOutRequest(GoodwaySSO.GWSSO.SetPreOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPreOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public SetPreOutRequestBody() {
        }
        
        public SetPreOutRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPreOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPreOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.SetPreOutResponseBody Body;
        
        public SetPreOutResponse() {
        }
        
        public SetPreOutResponse(GoodwaySSO.GWSSO.SetPreOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetPreOutResponseBody {
        
        public SetPreOutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPreOutExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPreOutEx", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.SetPreOutExRequestBody Body;
        
        public SetPreOutExRequest() {
        }
        
        public SetPreOutExRequest(GoodwaySSO.GWSSO.SetPreOutExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPreOutExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string logoutMethod;
        
        public SetPreOutExRequestBody() {
        }
        
        public SetPreOutExRequestBody(string passCode, string logoutMethod) {
            this.passCode = passCode;
            this.logoutMethod = logoutMethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPreOutExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPreOutExResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.SetPreOutExResponseBody Body;
        
        public SetPreOutExResponse() {
        }
        
        public SetPreOutExResponse(GoodwaySSO.GWSSO.SetPreOutExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetPreOutExResponseBody {
        
        public SetPreOutExResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshUserStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshUserState", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.RefreshUserStateRequestBody Body;
        
        public RefreshUserStateRequest() {
        }
        
        public RefreshUserStateRequest(GoodwaySSO.GWSSO.RefreshUserStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RefreshUserStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public RefreshUserStateRequestBody() {
        }
        
        public RefreshUserStateRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshUserStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.RefreshUserStateResponseBody Body;
        
        public RefreshUserStateResponse() {
        }
        
        public RefreshUserStateResponse(GoodwaySSO.GWSSO.RefreshUserStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RefreshUserStateResponseBody {
        
        public RefreshUserStateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.GetUserInfoRequestBody Body;
        
        public GetUserInfoRequest() {
        }
        
        public GetUserInfoRequest(GoodwaySSO.GWSSO.GetUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public GetUserInfoRequestBody() {
        }
        
        public GetUserInfoRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.GetUserInfoResponseBody Body;
        
        public GetUserInfoResponse() {
        }
        
        public GetUserInfoResponse(GoodwaySSO.GWSSO.GetUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserInfoResult;
        
        public GetUserInfoResponseBody() {
        }
        
        public GetUserInfoResponseBody(string GetUserInfoResult) {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.UpdateUserInfoRequestBody Body;
        
        public UpdateUserInfoRequest() {
        }
        
        public UpdateUserInfoRequest(GoodwaySSO.GWSSO.UpdateUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newUserInfo;
        
        public UpdateUserInfoRequestBody() {
        }
        
        public UpdateUserInfoRequestBody(string passCode, string newUserInfo) {
            this.passCode = passCode;
            this.newUserInfo = newUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.UpdateUserInfoResponseBody Body;
        
        public UpdateUserInfoResponse() {
        }
        
        public UpdateUserInfoResponse(GoodwaySSO.GWSSO.UpdateUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserInfoResult;
        
        public UpdateUserInfoResponseBody() {
        }
        
        public UpdateUserInfoResponseBody(bool UpdateUserInfoResult) {
            this.UpdateUserInfoResult = UpdateUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserData", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.GetUserDataRequestBody Body;
        
        public GetUserDataRequest() {
        }
        
        public GetUserDataRequest(GoodwaySSO.GWSSO.GetUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public GetUserDataRequestBody() {
        }
        
        public GetUserDataRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.GetUserDataResponseBody Body;
        
        public GetUserDataResponse() {
        }
        
        public GetUserDataResponse(GoodwaySSO.GWSSO.GetUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserDataResult;
        
        public GetUserDataResponseBody() {
        }
        
        public GetUserDataResponseBody(string GetUserDataResult) {
            this.GetUserDataResult = GetUserDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserData", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.UpdateUserDataRequestBody Body;
        
        public UpdateUserDataRequest() {
        }
        
        public UpdateUserDataRequest(GoodwaySSO.GWSSO.UpdateUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newUserData;
        
        public UpdateUserDataRequestBody() {
        }
        
        public UpdateUserDataRequestBody(string passCode, string newUserData) {
            this.passCode = passCode;
            this.newUserData = newUserData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.UpdateUserDataResponseBody Body;
        
        public UpdateUserDataResponse() {
        }
        
        public UpdateUserDataResponse(GoodwaySSO.GWSSO.UpdateUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserDataResult;
        
        public UpdateUserDataResponseBody() {
        }
        
        public UpdateUserDataResponseBody(bool UpdateUserDataResult) {
            this.UpdateUserDataResult = UpdateUserDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPropRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserProp", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.GetUserPropRequestBody Body;
        
        public GetUserPropRequest() {
        }
        
        public GetUserPropRequest(GoodwaySSO.GWSSO.GetUserPropRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserPropRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public GetUserPropRequestBody() {
        }
        
        public GetUserPropRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPropResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPropResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.GetUserPropResponseBody Body;
        
        public GetUserPropResponse() {
        }
        
        public GetUserPropResponse(GoodwaySSO.GWSSO.GetUserPropResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserPropResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserPropResult;
        
        public GetUserPropResponseBody() {
        }
        
        public GetUserPropResponseBody(string GetUserPropResult) {
            this.GetUserPropResult = GetUserPropResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPropRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserProp", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.UpdateUserPropRequestBody Body;
        
        public UpdateUserPropRequest() {
        }
        
        public UpdateUserPropRequest(GoodwaySSO.GWSSO.UpdateUserPropRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserPropRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newUserProp;
        
        public UpdateUserPropRequestBody() {
        }
        
        public UpdateUserPropRequestBody(string passCode, string newUserProp) {
            this.passCode = passCode;
            this.newUserProp = newUserProp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPropResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserPropResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.UpdateUserPropResponseBody Body;
        
        public UpdateUserPropResponse() {
        }
        
        public UpdateUserPropResponse(GoodwaySSO.GWSSO.UpdateUserPropResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserPropResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserPropResult;
        
        public UpdateUserPropResponseBody() {
        }
        
        public UpdateUserPropResponseBody(bool UpdateUserPropResult) {
            this.UpdateUserPropResult = UpdateUserPropResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDataNodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDataNode", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.GetUserDataNodeRequestBody Body;
        
        public GetUserDataNodeRequest() {
        }
        
        public GetUserDataNodeRequest(GoodwaySSO.GWSSO.GetUserDataNodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDataNodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        public GetUserDataNodeRequestBody() {
        }
        
        public GetUserDataNodeRequestBody(string passCode, string type, string name) {
            this.passCode = passCode;
            this.type = type;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDataNodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDataNodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.GetUserDataNodeResponseBody Body;
        
        public GetUserDataNodeResponse() {
        }
        
        public GetUserDataNodeResponse(GoodwaySSO.GWSSO.GetUserDataNodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDataNodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserDataNodeResult;
        
        public GetUserDataNodeResponseBody() {
        }
        
        public GetUserDataNodeResponseBody(string GetUserDataNodeResult) {
            this.GetUserDataNodeResult = GetUserDataNodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserDataNodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserDataNode", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.SetUserDataNodeRequestBody Body;
        
        public SetUserDataNodeRequest() {
        }
        
        public SetUserDataNodeRequest(GoodwaySSO.GWSSO.SetUserDataNodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserDataNodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string newDataNode;
        
        public SetUserDataNodeRequestBody() {
        }
        
        public SetUserDataNodeRequestBody(string passCode, string type, string name, string newDataNode) {
            this.passCode = passCode;
            this.type = type;
            this.name = name;
            this.newDataNode = newDataNode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserDataNodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserDataNodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoodwaySSO.GWSSO.SetUserDataNodeResponseBody Body;
        
        public SetUserDataNodeResponse() {
        }
        
        public SetUserDataNodeResponse(GoodwaySSO.GWSSO.SetUserDataNodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserDataNodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetUserDataNodeResult;
        
        public SetUserDataNodeResponseBody() {
        }
        
        public SetUserDataNodeResponseBody(bool SetUserDataNodeResult) {
            this.SetUserDataNodeResult = SetUserDataNodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface UserStateServiceSoapChannel : GoodwaySSO.GWSSO.UserStateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UserStateServiceSoapClient : System.ServiceModel.ClientBase<GoodwaySSO.GWSSO.UserStateServiceSoap>, GoodwaySSO.GWSSO.UserStateServiceSoap {
        
        public UserStateServiceSoapClient() {
        }
        
        public UserStateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserStateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserStateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserStateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.CreateUserStateResponse GoodwaySSO.GWSSO.UserStateServiceSoap.CreateUserState(GoodwaySSO.GWSSO.CreateUserStateRequest request) {
            return base.Channel.CreateUserState(request);
        }
        
        public string CreateUserState(string userInfo, string ip, string mac, string userId, string userName) {
            GoodwaySSO.GWSSO.CreateUserStateRequest inValue = new GoodwaySSO.GWSSO.CreateUserStateRequest();
            inValue.Body = new GoodwaySSO.GWSSO.CreateUserStateRequestBody();
            inValue.Body.userInfo = userInfo;
            inValue.Body.ip = ip;
            inValue.Body.mac = mac;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            GoodwaySSO.GWSSO.CreateUserStateResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).CreateUserState(inValue);
            return retVal.Body.CreateUserStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.CreateUserStateExResponse GoodwaySSO.GWSSO.UserStateServiceSoap.CreateUserStateEx(GoodwaySSO.GWSSO.CreateUserStateExRequest request) {
            return base.Channel.CreateUserStateEx(request);
        }
        
        public string CreateUserStateEx(string userInfo, string ip, string mac, string userId, string userName, string loginMethod) {
            GoodwaySSO.GWSSO.CreateUserStateExRequest inValue = new GoodwaySSO.GWSSO.CreateUserStateExRequest();
            inValue.Body = new GoodwaySSO.GWSSO.CreateUserStateExRequestBody();
            inValue.Body.userInfo = userInfo;
            inValue.Body.ip = ip;
            inValue.Body.mac = mac;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.loginMethod = loginMethod;
            GoodwaySSO.GWSSO.CreateUserStateExResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).CreateUserStateEx(inValue);
            return retVal.Body.CreateUserStateExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.CheckUserStateResponse GoodwaySSO.GWSSO.UserStateServiceSoap.CheckUserState(GoodwaySSO.GWSSO.CheckUserStateRequest request) {
            return base.Channel.CheckUserState(request);
        }
        
        public bool CheckUserState(string passCode) {
            GoodwaySSO.GWSSO.CheckUserStateRequest inValue = new GoodwaySSO.GWSSO.CheckUserStateRequest();
            inValue.Body = new GoodwaySSO.GWSSO.CheckUserStateRequestBody();
            inValue.Body.passCode = passCode;
            GoodwaySSO.GWSSO.CheckUserStateResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).CheckUserState(inValue);
            return retVal.Body.CheckUserStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.LogoutUserStateResponse GoodwaySSO.GWSSO.UserStateServiceSoap.LogoutUserState(GoodwaySSO.GWSSO.LogoutUserStateRequest request) {
            return base.Channel.LogoutUserState(request);
        }
        
        public bool LogoutUserState(string passCode) {
            GoodwaySSO.GWSSO.LogoutUserStateRequest inValue = new GoodwaySSO.GWSSO.LogoutUserStateRequest();
            inValue.Body = new GoodwaySSO.GWSSO.LogoutUserStateRequestBody();
            inValue.Body.passCode = passCode;
            GoodwaySSO.GWSSO.LogoutUserStateResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).LogoutUserState(inValue);
            return retVal.Body.LogoutUserStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.LogoutUserStateExResponse GoodwaySSO.GWSSO.UserStateServiceSoap.LogoutUserStateEx(GoodwaySSO.GWSSO.LogoutUserStateExRequest request) {
            return base.Channel.LogoutUserStateEx(request);
        }
        
        public bool LogoutUserStateEx(string passCode, string logoutMethod) {
            GoodwaySSO.GWSSO.LogoutUserStateExRequest inValue = new GoodwaySSO.GWSSO.LogoutUserStateExRequest();
            inValue.Body = new GoodwaySSO.GWSSO.LogoutUserStateExRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.logoutMethod = logoutMethod;
            GoodwaySSO.GWSSO.LogoutUserStateExResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).LogoutUserStateEx(inValue);
            return retVal.Body.LogoutUserStateExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.SetPreOutResponse GoodwaySSO.GWSSO.UserStateServiceSoap.SetPreOut(GoodwaySSO.GWSSO.SetPreOutRequest request) {
            return base.Channel.SetPreOut(request);
        }
        
        public void SetPreOut(string passCode) {
            GoodwaySSO.GWSSO.SetPreOutRequest inValue = new GoodwaySSO.GWSSO.SetPreOutRequest();
            inValue.Body = new GoodwaySSO.GWSSO.SetPreOutRequestBody();
            inValue.Body.passCode = passCode;
            GoodwaySSO.GWSSO.SetPreOutResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).SetPreOut(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.SetPreOutExResponse GoodwaySSO.GWSSO.UserStateServiceSoap.SetPreOutEx(GoodwaySSO.GWSSO.SetPreOutExRequest request) {
            return base.Channel.SetPreOutEx(request);
        }
        
        public void SetPreOutEx(string passCode, string logoutMethod) {
            GoodwaySSO.GWSSO.SetPreOutExRequest inValue = new GoodwaySSO.GWSSO.SetPreOutExRequest();
            inValue.Body = new GoodwaySSO.GWSSO.SetPreOutExRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.logoutMethod = logoutMethod;
            GoodwaySSO.GWSSO.SetPreOutExResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).SetPreOutEx(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.RefreshUserStateResponse GoodwaySSO.GWSSO.UserStateServiceSoap.RefreshUserState(GoodwaySSO.GWSSO.RefreshUserStateRequest request) {
            return base.Channel.RefreshUserState(request);
        }
        
        public void RefreshUserState(string passCode) {
            GoodwaySSO.GWSSO.RefreshUserStateRequest inValue = new GoodwaySSO.GWSSO.RefreshUserStateRequest();
            inValue.Body = new GoodwaySSO.GWSSO.RefreshUserStateRequestBody();
            inValue.Body.passCode = passCode;
            GoodwaySSO.GWSSO.RefreshUserStateResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).RefreshUserState(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.GetUserInfoResponse GoodwaySSO.GWSSO.UserStateServiceSoap.GetUserInfo(GoodwaySSO.GWSSO.GetUserInfoRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public string GetUserInfo(string passCode) {
            GoodwaySSO.GWSSO.GetUserInfoRequest inValue = new GoodwaySSO.GWSSO.GetUserInfoRequest();
            inValue.Body = new GoodwaySSO.GWSSO.GetUserInfoRequestBody();
            inValue.Body.passCode = passCode;
            GoodwaySSO.GWSSO.GetUserInfoResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).GetUserInfo(inValue);
            return retVal.Body.GetUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.UpdateUserInfoResponse GoodwaySSO.GWSSO.UserStateServiceSoap.UpdateUserInfo(GoodwaySSO.GWSSO.UpdateUserInfoRequest request) {
            return base.Channel.UpdateUserInfo(request);
        }
        
        public bool UpdateUserInfo(string passCode, string newUserInfo) {
            GoodwaySSO.GWSSO.UpdateUserInfoRequest inValue = new GoodwaySSO.GWSSO.UpdateUserInfoRequest();
            inValue.Body = new GoodwaySSO.GWSSO.UpdateUserInfoRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.newUserInfo = newUserInfo;
            GoodwaySSO.GWSSO.UpdateUserInfoResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).UpdateUserInfo(inValue);
            return retVal.Body.UpdateUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.GetUserDataResponse GoodwaySSO.GWSSO.UserStateServiceSoap.GetUserData(GoodwaySSO.GWSSO.GetUserDataRequest request) {
            return base.Channel.GetUserData(request);
        }
        
        public string GetUserData(string passCode) {
            GoodwaySSO.GWSSO.GetUserDataRequest inValue = new GoodwaySSO.GWSSO.GetUserDataRequest();
            inValue.Body = new GoodwaySSO.GWSSO.GetUserDataRequestBody();
            inValue.Body.passCode = passCode;
            GoodwaySSO.GWSSO.GetUserDataResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).GetUserData(inValue);
            return retVal.Body.GetUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.UpdateUserDataResponse GoodwaySSO.GWSSO.UserStateServiceSoap.UpdateUserData(GoodwaySSO.GWSSO.UpdateUserDataRequest request) {
            return base.Channel.UpdateUserData(request);
        }
        
        public bool UpdateUserData(string passCode, string newUserData) {
            GoodwaySSO.GWSSO.UpdateUserDataRequest inValue = new GoodwaySSO.GWSSO.UpdateUserDataRequest();
            inValue.Body = new GoodwaySSO.GWSSO.UpdateUserDataRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.newUserData = newUserData;
            GoodwaySSO.GWSSO.UpdateUserDataResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).UpdateUserData(inValue);
            return retVal.Body.UpdateUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.GetUserPropResponse GoodwaySSO.GWSSO.UserStateServiceSoap.GetUserProp(GoodwaySSO.GWSSO.GetUserPropRequest request) {
            return base.Channel.GetUserProp(request);
        }
        
        public string GetUserProp(string passCode) {
            GoodwaySSO.GWSSO.GetUserPropRequest inValue = new GoodwaySSO.GWSSO.GetUserPropRequest();
            inValue.Body = new GoodwaySSO.GWSSO.GetUserPropRequestBody();
            inValue.Body.passCode = passCode;
            GoodwaySSO.GWSSO.GetUserPropResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).GetUserProp(inValue);
            return retVal.Body.GetUserPropResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.UpdateUserPropResponse GoodwaySSO.GWSSO.UserStateServiceSoap.UpdateUserProp(GoodwaySSO.GWSSO.UpdateUserPropRequest request) {
            return base.Channel.UpdateUserProp(request);
        }
        
        public bool UpdateUserProp(string passCode, string newUserProp) {
            GoodwaySSO.GWSSO.UpdateUserPropRequest inValue = new GoodwaySSO.GWSSO.UpdateUserPropRequest();
            inValue.Body = new GoodwaySSO.GWSSO.UpdateUserPropRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.newUserProp = newUserProp;
            GoodwaySSO.GWSSO.UpdateUserPropResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).UpdateUserProp(inValue);
            return retVal.Body.UpdateUserPropResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.GetUserDataNodeResponse GoodwaySSO.GWSSO.UserStateServiceSoap.GetUserDataNode(GoodwaySSO.GWSSO.GetUserDataNodeRequest request) {
            return base.Channel.GetUserDataNode(request);
        }
        
        public string GetUserDataNode(string passCode, string type, string name) {
            GoodwaySSO.GWSSO.GetUserDataNodeRequest inValue = new GoodwaySSO.GWSSO.GetUserDataNodeRequest();
            inValue.Body = new GoodwaySSO.GWSSO.GetUserDataNodeRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.type = type;
            inValue.Body.name = name;
            GoodwaySSO.GWSSO.GetUserDataNodeResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).GetUserDataNode(inValue);
            return retVal.Body.GetUserDataNodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoodwaySSO.GWSSO.SetUserDataNodeResponse GoodwaySSO.GWSSO.UserStateServiceSoap.SetUserDataNode(GoodwaySSO.GWSSO.SetUserDataNodeRequest request) {
            return base.Channel.SetUserDataNode(request);
        }
        
        public bool SetUserDataNode(string passCode, string type, string name, string newDataNode) {
            GoodwaySSO.GWSSO.SetUserDataNodeRequest inValue = new GoodwaySSO.GWSSO.SetUserDataNodeRequest();
            inValue.Body = new GoodwaySSO.GWSSO.SetUserDataNodeRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.type = type;
            inValue.Body.name = name;
            inValue.Body.newDataNode = newDataNode;
            GoodwaySSO.GWSSO.SetUserDataNodeResponse retVal = ((GoodwaySSO.GWSSO.UserStateServiceSoap)(this)).SetUserDataNode(inValue);
            return retVal.Body.SetUserDataNodeResult;
        }
    }
}
